### ISSUE TITLE
Установка php на MacOS

### ISSUE THREAD

**Issue by voronkovich** [htmlacademy-php/24223-yeticave#3]
@ilovebeatles, В академии советуют использовать этот способ https://php-osx.liip.ch/
Кстати, в макоси есть встроенный по умолчанию php?

**Comment by ilovebeatles** [comment]
@voronkovich Как говорил, php уже установил.

**Comment by voronkovich** [comment]
@ilovebeatles, один из наставников в академии также советовал https://www.mamp.info
